Entity = {
    SetIsPredictingMovement = function(...) end,
    AddRoadManager = function(...) end,
    AddMiniMap = function(...) end,
    AddMiniMapEntity = function(...) end,
    AddFollower = function(...) end,
    AddAnimState = function(...) end,
    GetHistoryData = function(...) end,

    -- I dunno what this does but I do know if only takes a `self` parameter.
    -- see `scripts/video.lua`.
    AddVideoWidget = function(self)
    end,
    RemoveTag = function(...) end,
    Show = function(...) end,
    SetParent = function(...) end,
    AddEnvelopeManager = function(...) end,
    SetClickable = function(...) end,
    AddMapGenSim = function(...) end,
    GetDebugString = function(...) end,
    FlattenMovementPrediction = function(...) end,
    AddLabel = function(...) end,
    AddPhysics = function(...) end,
    AddPhysicsWaker = function(...) end,
    GetPlatform = function(...) end,
    SetPrefabName = function(...) end,
    WorldToLocalSpace = function(...) end,
    CanPredictMovement = function(...) end,
    IsValid = function(...) end,
    SetCanSleep = function(...) end,
    AddLight = function(...) end,
    LocalToWorldSpaceIncParent = function(...) end,
    GetPrefabName = function(...) end,
    AddTextEditWidget = function(...) end,
    AddNetwork = function(...) print('scripts/entityscript.lua:174') end,
    SetSelected = function(...) end,
    AddTextWidget = function(...) end,
    AddPostProcessor = function(...) end,
    AddTag = function(...) end,
    EnableMovementPrediction = function(...) end,
    AddWaveComponent = function(...) end,
    Hide = function(...) end,
    AddGroundCreep = function(...) end,
    AddShardNetwork = function(...) end,
    LocalToWorldSpace = function(...) end,
    GetName = function(...) end,
    AddSoundEmitter = function(...) end,
    IsVisible = function(...) end,
    AddShardClient = function(...) end,
    SetName = function(...) end,
    AddTransform = function(...) end,
    AddMapExplorer = function(...) end,
    AddDebugRender = function(...) end,
    GetAnimStateData = function(...) end,
    GetParent = function(...) end,
    AddLightWatcher = function(...) end,
    HasTag = function(...) end,
    FrustumCheck = function(...) end,
    SetPlatform = function(...) end,
    MoveToBack = function(...) end,
    AddDynamicShadow = function(...) end,
    AddStaticShadow = function(...) end,
    AddUITransform = function(...) end,
    AddClientSleepable = function(...) end,
    AddMap = function(...) end,
    SetPristine = function(...) end,
    AddPathfinder = function(...) end,
    SetAABB = function(...) end,
    CallPrefabConstructionComplete = function(...) end,
    AddShadowManager = function(...) end,
    SetInLimbo = function(...) end,

    -- Returns the GUID of the caller.
    -- TODO Determine if GUID is a number or a string.
    GetGUID = function(self, ...) 
        return 0
    end,
    MoveToFront = function(...) end,
    AddImage = function(...) end,
    AddAccountManager = function(...) end,
    AddParticleEmitter = function(...) end,
    AddImageWidget = function(...) end,
    AddServerNonSleepable = function(...) end,
    Retire = function(...) end,
    AddGroundCreepEntity = function(...) end,
    AddTwitchOptions = function(...) end,
    AddGraphicsOptions = function(...) end,
    AddMapLayerManager = function(...) end,
    AddFontManager = function(...) end,
    FlushLocalDirtyNetVars = function(...) end,
    IsAwake = function(...) end,
    AddVFXEffect = function(...) end
}
