-- TODO determine if the one starting with `The` is the correct one to reference.

TheInputProxy = {
    GetInputDeviceCount = function(...) end,
    GetInputDeviceName = function(...) end,
    LoadControls = function(...) end,
    CloseVirtualKeyboard = function(...) end,
    SetCursorVisible = function(...) end,
    IsAnyControllerActive = function(...) end,
    IsAnyControllerConnected = function(...) end,
    LoadDefaultControlMapping = function(...) end,
    IsInputDeviceEnabled = function(...) end,
    FlushInput = function(...) end,
    GetLocalizedControl = function(...) end,
    StopMappingControls = function(...) end,
    GetOSCursorPos = function(...) end,
    OpenVirtualKeyboard = function(...) end,
    EnableVibration = function(...) end,
    CancelMapping = function(...) end,
    IsAnyInputDeviceConnected = function(...) end,
    IsInputDeviceConnected = function(...) end,
    StartMappingControls = function(...) end,
    HasMappingChanged = function(...) end,
    EnableInputDevice = function(...) end,
    AddVibration = function(...) end,
    UnMapControl = function(...) end,
    GetInputDeviceType = function(...) end,
    SetOSCursorPos = function(...) end,
    RemoveVibration = function(...) end,
    ApplyControlMapping = function(...) end,
    StopVibration = function(...) end,
    SaveControls = function(...) end,
    MapControl = function(...) end,
    LoadCurrentControlMapping = function(...) end,
    GetLastActiveControllerIndex = function(...) end
}
InputProxy = TheInputProxy
