SystemService = {
    StopDedicatedServers = function(...) end,
    IsStorageAvailable = function(...) end,
    StartDedicatedServers = function(...) end,
    AdjustDisplaySafeArea = function(...) end,
    EnableStorage = function(...) end,
    DidBugReportSucceed = function(...) end,
    EnableAutosave = function(...) end,
    PrepareStorage = function(...) end,
    GetBugReportUserCode = function(...) end,
    ClearLastOperation = function(...) end,
    GotoStorePageROG = function(...) end,
    IsStorageEnabled = function(...) end,
    RetryOperation = function(...) end,
    IsDisplaySafeAreaAdjusted = function(...) end,
    GetLastOperation = function(...) end,
    IsBugReportRunning = function(...) end,
    IsAutosaveEnabled = function(...) end,
    HasFocus = function(...) end,
    OverwriteStorage = function(...) end,
    SetStalling = function(...) end,
    FileBugReport = function(...) end
}
TheSystemService = SystemService
